package mx.ipn.logica.ALexico;

public enum Token {
  ASIGNAR,IGUAL,DIFERENTE,SUMA,MUL,RESTA,DIV,COMILLA,PARENTESIS_ABIERTO,PARENTESIS_CERRADO,MAYOR,MENOR,
  CORCHETE_ABIERTO,CORCHETE_CERRADO,LLAVE_ABIERTA,LLAVE_CERRADA,PUNTO_Y_COMA,PALABRA_RESERVADA,
  INT,ID,ERROR
}
